"""Frozen Linkup product and ICP context injected into every prospect brief.

Built by desk research on 2026-09-21 from the public sources listed in LINKUP_CONTEXT["sources"],
then independently re-verified claim by claim. It is NOT generated by any provider in the
comparison, so it cannot advantage one provider's evidence over another.

This block is byte-identical across all five providers in a run. CONTEXT_SHA256 is recorded in
the run manifest and folded into the prompt hash, so a run made under a different context version
is visibly not comparable with an earlier one.

To update: edit LINKUP_CONTEXT. Vendor marketing should be labelled as a vendor claim.
"""
from __future__ import annotations

import hashlib
import json

CONTEXT_VERSION = "1.2"


LINKUP_CONTEXT = {   'context_version': '1.2',
    'built_at': '2026-09-21',
    'built_by': 'Desk research from public sources. Not generated by any provider in the comparison.',
    'review_status': 'DRAFT - requires human review before use',
    'reviewed_on': None,
    'reviewed_by': None,
    'usage_rules': [   'This block describes Linkup, the vendor. It is NOT evidence about the '
                       'prospect. Never cite a CTX- source to support a claim about the prospect '
                       'company.',
                       'Vendor claims are labelled. Do not restate a vendor claim as established fact, '
                       'in the brief or in the email.',
                       'Benchmark results are self-run by Linkup unless marked independent. Never '
                       'present them as neutral third-party validation.',
                       'Do not claim Linkup is more accurate, faster or better than a named '
                       'competitor. State capabilities, not superiority.',
                       'Use this block to judge fit and to write a specific use case. Do not use it to '
                       'assume the prospect is dissatisfied with anything.'],
    'entity': {   'name': 'Linkup',
                  'domain': 'linkup.so',
                  'description': 'Web search and retrieval API for AI applications and agents.',
                  'disambiguation': [   'linkup.com (LinkUp) is a DIFFERENT company selling '
                                        'job-postings market data. Evidence from linkup.com is not '
                                        'about this Linkup.',
                                        'Also distinct from LinkedIn tooling such as Linked Helper.',
                                        'When retrieved evidence concerns linkup.com or a jobs-data '
                                        'product, flag it as wrong-entity evidence.']},
    'company': {   'founders': [   {   'name': 'Philippe Mizrahi',
                                       'role': 'CEO and co-founder',
                                       'source': 'CTX-04',
                                       'background': 'Previously built graph-based data search systems '
                                                     'at Lyft'},
                                   {   'name': 'Denis',
                                       'role': 'CTO, previously built a neural music search engine '
                                               'acquired by Spotify',
                                       'source': 'CTX-04',
                                       'name_note': 'Surname not published by Linkup'},
                                   {   'name': 'Boris',
                                       'role': 'COO, previously McKinsey',
                                       'source': 'CTX-04',
                                       'name_note': 'Surname not published by Linkup'}],
                   'funding': {   'round': '$10M seed',
                                  'announced': '2026-03-03',
                                  'lead': 'Gradient',
                                  'participants': 'Investors and founders from Mistral, Datadog, Deel '
                                                  'and Dataiku',
                                  'source': 'CTX-04'},
                   'stage_implication': 'Seed-stage, France-linked, selling developer infrastructure '
                                        'into both AI-native startups and large enterprises. Expect a '
                                        'small revenue team and a high bar on evidence quality per '
                                        'conversation.'},
    'product': {   'endpoints': [   {   'name': 'Search',
                                        'input': 'query',
                                        'output': 'ranked URLs, sourced answer, or structured JSON',
                                        'latency': 'under 200ms to about 30s depending on depth',
                                        'sync': True,
                                        'source': 'CTX-02'},
                                    {   'name': 'Fetch',
                                        'input': 'URL',
                                        'output': 'clean markdown or typed JSON',
                                        'latency': 'about 1s',
                                        'sync': True,
                                        'source': 'CTX-02'},
                                    {   'name': 'Research',
                                        'input': 'query',
                                        'output': 'detailed report with citations',
                                        'latency': '2-20 minutes',
                                        'sync': False,
                                        'source': 'CTX-02'},
                                    {   'name': 'Tasks',
                                        'input': 'batch of up to 100 calls',
                                        'output': 'batch results',
                                        'latency': '1s to 20 minutes',
                                        'sync': False,
                                        'source': 'CTX-02'},
                                    {   'name': 'Extract',
                                        'input': 'seed URL plus query',
                                        'output': 'structured rows',
                                        'status': 'closed beta',
                                        'source': 'CTX-02'}],
                   'search_depths': ['flash', 'fast', 'standard', 'deep'],
                   'search_output_types': ['searchResults', 'sourcedAnswer', 'structured'],
                   'notable_parameters': [   'includeDomains (up to 100)',
                                             'excludeDomains',
                                             'fromDate',
                                             'toDate',
                                             'maxResults',
                                             'includeImages',
                                             'includeInlineCitations',
                                             'includeSources',
                                             'structuredOutputSchema'],
                   'source': 'CTX-03',
                   'deployment_and_compliance': {   'options': [   'Private Index',
                                                                   'Bring Your Own Cloud / on-premise',
                                                                   'dedicated refresh rates',
                                                                   'Single Sign On'],
                                                    'certifications_claimed': [   'Zero Data Retention',
                                                                                  'SOC 2 Type II',
                                                                                  'HIPAA',
                                                                                  '99.9% uptime',
                                                                                  'SLA'],
                                                    'label': 'vendor claim',
                                                    'source': 'CTX-01, CTX-05',
                                                    'note': 'All vendor-stated. IP whitelisting '
                                                            'appears in some plan descriptions but was '
                                                            'not confirmed on the homepage or pricing '
                                                            'page; treat as unconfirmed.'},
                   'what_this_means_commercially': 'Linkup sells three different things at three '
                                                   'different price points: cheap high-volume '
                                                   'grounding (flash/fast), standard agent search, and '
                                                   "expensive async deep research. A prospect's "
                                                   'workload shape determines which one, and therefore '
                                                   'the deal size.'},
    'pricing': {   'free_tier': '4,000 queries free',
                   'search_per_request': '$0.005 - $0.006 for Fast, Standard and Deep. Flash pricing '
                                         'is not published.',
                   'fetch_per_request': '$0.001 - $0.006',
                   'research_per_request': '$0.25 - $2.50',
                   'startup_program': 'Apply for $5,000 in credits',
                   'enterprise': 'Contact sales. Custom pricing, personalised indexes, dedicated '
                                 'refresh rates, private environment.',
                   'source': 'CTX-05',
                   'deal_shape_implication': 'Self-serve usage is small-ticket. Meaningful contracts '
                                             'come from either high-volume agent traffic (millions of '
                                             'searches) or enterprise requirements: private index, '
                                             'BYOC, ZDR, SLA. Qualifying should establish which of the '
                                             'two a prospect is.'},
    'proof': {   'named_customers': [   'Sapiom',
                                        'H Company',
                                        'Artisan',
                                        'Blackfin',
                                        'Legora',
                                        'SNCF',
                                        'Barebone',
                                        'GitGuardian',
                                        'Omniscient AI',
                                        'Pennylane',
                                        'Boulanger',
                                        'Floquer',
                                        'KPMG',
                                        'one unnamed enterprise banking client'],
                 'named_customers_label': 'companies with a published Linkup case study',
                 'source': 'CTX-01, CTX-06',
                 'case_studies': [   {   'customer': 'Artisan',
                                         'segment': 'AI BDR / outbound automation',
                                         'problem': 'Self-serve onboarding required customers to '
                                                    'manually gather company context, taking up to an '
                                                    'hour and delaying the first campaign.',
                                         'how_they_use_it': 'Search endpoint in standard and deep '
                                                            'modes for structured company context at '
                                                            'signup; Tasks endpoint for async batch '
                                                            'enrichment of account lists; real-time '
                                                            'signals on news, hiring, product launches '
                                                            'and leadership changes for '
                                                            'personalisation.',
                                         'stated_outcome': 'Enrichment reduced from 10+ minutes to '
                                                           'under 10 seconds; self-serve activation '
                                                           'under 10 minutes.',
                                         'label': 'vendor case study, customer-attributed quote',
                                         'source': 'CTX-06',
                                         'why_it_matters': 'This is the closest analogue to a GTM '
                                                           'prospect. Reuse this shape when the '
                                                           'prospect builds outbound, enrichment or '
                                                           'account research.'},
                                     {   'customer': 'Legora',
                                         'segment': 'Legal AI',
                                         'use_case': 'Production web search infrastructure deployed '
                                                     'globally',
                                         'source': 'CTX-07'},
                                     {   'customer': 'Blackfin',
                                         'segment': 'Investment intelligence',
                                         'use_case': 'Agentic deal sourcing',
                                         'source': 'CTX-07'},
                                     {   'customer': 'GitGuardian',
                                         'segment': 'Cybersecurity',
                                         'use_case': 'Real-time corporate intelligence for breach '
                                                     'detection',
                                         'source': 'CTX-07'},
                                     {   'customer': 'Pennylane',
                                         'segment': 'Sales enablement',
                                         'use_case': 'Pipeline enrichment and real-time web intent '
                                                     'detection',
                                         'source': 'CTX-07'},
                                     {   'customer': 'SNCF',
                                         'segment': 'Enterprise / transport',
                                         'use_case': 'Secure enterprise AI search',
                                         'source': 'CTX-07'}],
                 'benchmarks': {   'caveat': 'All figures below are published and self-run by Linkup, '
                                             'on public benchmark suites. Treat as vendor claims. Two '
                                             'use external methodology as noted.',
                                   'results': [   {   'benchmark': 'SimpleQA (OpenAI suite)',
                                                      'linkup_config': 'Fast',
                                                      'score': '94% F1',
                                                      'compared_against': [   'Perplexity Sonar',
                                                                              'Gemini 3 Flash',
                                                                              'Serper',
                                                                              'Tavily',
                                                                              'Exa'],
                                                      'run_by': 'Linkup',
                                                      'competitor_scores': 'Perplexity Sonar 87, '
                                                                           'Gemini 3 Flash 85, Serper '
                                                                           'Fast 83, Tavily Fast 79, '
                                                                           'Exa Fast 63',
                                                      'note': 'This result is for the Fast tier. '
                                                              'Linkup has not published a SimpleQA '
                                                              'score for Flash. Do not attribute it to '
                                                              'Flash.'},
                                                  {   'benchmark': 'SealQA-0',
                                                      'linkup_config': 'Research',
                                                      'score': '61%',
                                                      'compared_against': [   'Parallel Ultra 8X',
                                                                              'GPT-5',
                                                                              'Exa Research Pro',
                                                                              'Perplexity DR',
                                                                              'Tavily Research'],
                                                      'methodology': 'external, '
                                                                     'arxiv.org/abs/2506.01062',
                                                      'run_by': 'Linkup',
                                                      'competitor_scores': 'Parallel Ultra 8X 56, '
                                                                           'GPT-5 48, Exa Research Pro '
                                                                           '45, Perplexity DR 38, '
                                                                           'Tavily Research 24'},
                                                  {   'benchmark': 'GTM use case',
                                                      'scores': 'Freshness 74%, Enrichment 94%, '
                                                                'Richness 64.8, Answer quality 80.7%, '
                                                                'Funding 83%',
                                                      'compared_against': [   'Exa',
                                                                              'Perplexity',
                                                                              'Parallel'],
                                                      'ground_truth': 'profile DB and Crunchbase, '
                                                                      'described by Linkup as '
                                                                      'independent ground truth. '
                                                                      'Linkup ran the comparison.',
                                                      'run_by': 'Linkup'},
                                                  {   'benchmark': 'Legal (Crosby RedlineBench, '
                                                                   '3-judge grading across 140 tasks)',
                                                      'score': 'Linkup + GPT-5.5 at 58.6% vs GPT-5.5 '
                                                               'alone at 50.5%',
                                                      'run_by': 'Linkup, external grading'},
                                                  {   'benchmark': 'Finance (FinSearchComp: 635 '
                                                                   'questions, gold answers against '
                                                                   'SEC filings and exchange data)',
                                                      'score': 'Research T2 82.4%, T3 58.3%',
                                                      'compared_against': [   'Parallel',
                                                                              'Perplexity',
                                                                              'Tavily',
                                                                              'Exa'],
                                                      'run_by': 'Linkup'}],
                                   'no_dates_published': True,
                                   'source': 'CTX-08'},
                 'logos_only': {   'names': [   'McKinsey & Company',
                                                'EY',
                                                'Cohere',
                                                'Databricks',
                                                'Die Bundesregierung',
                                                'Amo'],
                                   'label': 'homepage logos with no published case study',
                                   'caution': 'A logo is not a defensible customer claim. Do not '
                                              'describe these as customers in conversation; say Linkup '
                                              'displays them on its site.',
                                   'source': 'CTX-01'}},
    'positioning': {   'claimed_differentiators': [   {   'claim': 'Index control: tune the index, '
                                                                   'pick the sources, set the '
                                                                   'freshness',
                                                          'label': 'vendor claim',
                                                          'source': 'CTX-01'},
                                                      {   'claim': 'Accuracy on factual-QA benchmarks '
                                                                   'for search-augmented systems',
                                                          'label': 'vendor claim, self-run',
                                                          'source': 'CTX-08'},
                                                      {   'claim': 'Sub-200ms median (p50) latency at '
                                                                   'the Flash tier, self-measured '
                                                                   'client-side',
                                                          'label': 'vendor claim',
                                                          'source': 'CTX-09'},
                                                      {   'claim': 'Deployment and compliance '
                                                                   'controls: private index, BYOC, '
                                                                   'ZDR, SOC 2 Type II',
                                                          'label': 'vendor claim',
                                                          'source': 'CTX-01'}],
                       'competitive_set': [   {   'name': 'Tavily',
                                                  'status': 'Acquired by Nebius, announced 2026-02-10. '
                                                            'Brand and team continue under Nebius; CEO '
                                                            'Rotem Weiss joined Nebius. Deal value not '
                                                            'disclosed by Nebius; Bloomberg reported '
                                                            '$275M.',
                                                  'source': 'CTX-10, CTX-11',
                                                  'sales_relevance': 'A prospect on Tavily may now be '
                                                                     'evaluating vendor independence, '
                                                                     'roadmap direction or cloud '
                                                                     'lock-in. This is a reason to '
                                                                     'have a conversation, not proof '
                                                                     'of dissatisfaction.'},
                                              {   'name': 'Exa',
                                                  'status': 'Independent search API, embeddings-based '
                                                            'retrieval, research tier',
                                                  'sales_relevance': 'Common incumbent among AI-native '
                                                                     'teams.'},
                                              {   'name': 'Parallel',
                                                  'status': 'Independent, objective-based search and '
                                                            'deep research tiers',
                                                  'sales_relevance': 'Strong in structured research '
                                                                     'workloads.'},
                                              {   'name': 'Perplexity Sonar',
                                                  'status': 'Answer-oriented API',
                                                  'sales_relevance': 'Often chosen when the team wants '
                                                                     'an answer rather than sources.'},
                                              {   'name': 'Brave Search API',
                                                  'status': 'General web search index',
                                                  'sales_relevance': 'Chosen on price and index '
                                                                     'independence rather than agent '
                                                                     'features.'},
                                              {   'name': 'Serper / SerpAPI',
                                                  'status': 'SERP scraping layer',
                                                  'sales_relevance': 'The cheap incumbent to displace '
                                                                     'on quality, not price.'},
                                              {   'name': 'Build in-house on a search index',
                                                  'status': 'Common at larger engineering orgs',
                                                  'sales_relevance': 'The real competitor in '
                                                                     'enterprise deals is often an '
                                                                     'internal build.'}]},
    'icp': {   'core_pattern': 'A company that SHIPS a product or internal system whose output depends '
                               'on information from outside its own four walls - the public web, news, '
                               'company and people data, filings, documentation - and that must be '
                               'current and attributable. Linkup sells the retrieval layer such a '
                               'company would otherwise build, scrape, staff or buy from data vendors.',
               'how_to_apply': [   "THIS IS A BUYER TEST. Ask only: would this company's product be "
                                   'better, cheaper or faster if its external information came from '
                                   'Linkup? Never ask whether the company resembles Linkup or sells '
                                   'what Linkup sells. Selling web retrieval is what makes a company a '
                                   "COMPETITOR, not a customer. 'They do not provide a web search API' "
                                   'is a reason they might BUY one.',
                                   "The prospect does not need to use the words 'web search', "
                                   "'retrieval', 'crawling' or 'API'. Enrichment, account research, "
                                   'company and contact data, intent signals, monitoring, screening, '
                                   "due diligence, sourcing, competitive tracking and 'we pull from N "
                                   "data vendors' are all external-information workloads.",
                                   'Buying from data vendors, scraping, or paying people to research '
                                   'are the incumbent approaches Linkup displaces. Finding one is a '
                                   'POSITIVE signal about the workload, not evidence the company is '
                                   'well served.',
                                   'No evidence of any current search or data provider is NOT an '
                                   'anti-signal. It usually means the workload is handled by vendors, '
                                   'scraping or humans, which is greenfield. Only a documented '
                                   'anti-signal disqualifies.',
                                   'Unknown query volume, budget, procurement path, contract terms or '
                                   'compliance posture NEVER lower the verdict. They are almost never '
                                   'public. They belong in evidence_gaps and the qualification '
                                   'questions.'],
               'worked_patterns': [   {   'pattern': 'GTM, outbound or revenue platform doing account '
                                                     'research and enrichment at list scale',
                                          'linkup_customers': ['Artisan', 'Pennylane'],
                                          'note': 'Enrichment at signup, account lists built from many '
                                                  'sources, real-time signals on news, hiring, '
                                                  'funding, product launches and leadership changes. A '
                                                  'prospect of this shape is a fit even when it buys '
                                                  'its data from vendors today and never mentions web '
                                                  'search.'},
                                      {   'pattern': 'Vertical AI copilot where a stale or wrong '
                                                     'citation is expensive',
                                          'linkup_customers': ['Legora', 'Blackfin', 'GitGuardian'],
                                          'note': 'Legal, investment, security, compliance, KYB and '
                                                  'diligence workloads.'},
                                      {   'pattern': 'Agent or computer-use platform needing live '
                                                     'grounding at production scale',
                                          'linkup_customers': ['H Company', 'Sapiom']},
                                      {   'pattern': 'Large enterprise deploying internal AI '
                                                     'assistants under data constraints',
                                          'linkup_customers': ['KPMG', 'SNCF'],
                                          'note': 'Drives the private index, BYOC and ZDR conversation '
                                                  'rather than per-query pricing.'}],
               'buying_signals': [   'Ships an agent, copilot, research or enrichment product whose '
                                     'output depends on information about the outside world',
                                     'Builds or refreshes lists, profiles or records about companies '
                                     'or people',
                                     'Acts on external events: funding rounds, hiring, launches, '
                                     'leadership changes, news, filings',
                                     'Sells into a domain where staleness or a wrong citation is '
                                     'expensive: legal, finance, compliance, KYB and KYC, security, '
                                     'healthcare',
                                     'Publicly documents citations or source attribution as a product '
                                     'feature',
                                     'Currently buys from data vendors, runs scrapers, or uses a SERP '
                                     'or general search API',
                                     'Recent launch of an agentic, research or enrichment feature, or '
                                     'a move from demo to production',
                                     'Hiring for AI platform, retrieval, RAG or data infrastructure '
                                     'roles',
                                     'Enterprise or public-sector customers that force data residency, '
                                     'retention or procurement requirements'],
               'anti_signals': [   'Sells a competing web search, crawling or retrieval API. This '
                                   'company is a competitor, not a prospect.',
                                   'Operates its own web index or crawler at scale',
                                   "The product works only on the customer's private corpus or "
                                   'first-party data, with no external component',
                                   'No shipped software product at all, for example a pure services or '
                                   'consultancy business',
                                   'A documented regulatory or contractual prohibition on third-party '
                                   'web retrieval',
                                   'Usage so small that the free tier covers it indefinitely'],
               'not_anti_signals': [   'No public evidence of any search API or data provider. This is '
                                       'greenfield.',
                                       'Buys company or contact data from vendors today. This is the '
                                       'incumbent approach Linkup displaces.',
                                       "Never uses the words 'web search' or 'retrieval' in its "
                                       'marketing.',
                                       'Unknown query volume, pricing tier, compliance needs or buying '
                                       'intent.',
                                       'Does not sell an API itself.'],
               'buyer_roles_to_investigate': [   'Founder or CTO at seed to Series B AI-native '
                                                 'companies',
                                                 'Head of AI, Head of Applied AI or AI Platform lead '
                                                 'in mid-size and enterprise',
                                                 'Engineering lead owning the agent, RAG, enrichment '
                                                 'or retrieval pipeline',
                                                 'Product lead for the research, enrichment or copilot '
                                                 'surface',
                                                 'In enterprise, expect security, procurement and '
                                                 'data-protection stakeholders on the path'],
               'qualification_dimensions': {   'note': 'These are established in a CONVERSATION. Their '
                                                       'absence from public evidence is expected and '
                                                       'must not lower the verdict. Use them to write '
                                                       'the qualification questions.',
                                               'dimensions': [   'Workload shape: real-time agent '
                                                                 'grounding, batch enrichment, or '
                                                                 'async deep research. Each maps to a '
                                                                 'different endpoint and price point.',
                                                                 'Volume: queries or records per '
                                                                 'month, and whether it grows with '
                                                                 'usage',
                                                                 'Current approach: build, scrape, '
                                                                 'data vendors, or a named API, and '
                                                                 'what it costs in money and '
                                                                 'maintenance',
                                                                 'Quality pain: freshness, coverage, '
                                                                 'citation reliability, latency, or '
                                                                 'cost',
                                                                 'Constraints: data residency, '
                                                                 'retention policy, on-prem, SLA, '
                                                                 'procurement path',
                                                                 'Trigger: what changed recently that '
                                                                 'makes this worth solving now']},
               'verdict_guidance': {   'strong': 'A documented product or workflow that depends on '
                                                 'external information, AND at least one of: scale '
                                                 '(list-level, per-user or per-query volume), a '
                                                 'costly-error domain, or a recent trigger. All '
                                                 'supported by cited evidence.',
                                       'plausible': 'A documented product or workflow that depends on '
                                                    'external information, with scale, trigger or '
                                                    'constraints not established. This is the correct '
                                                    'verdict for a well-documented company whose '
                                                    'product shape matches, and it should be common.',
                                       'weak': 'Only indirect or inferred dependence on external '
                                               'information, or a dependence narrow enough that the '
                                               'free tier would cover it.',
                                       'not_a_fit': 'A documented anti-signal from the anti_signals '
                                                    'list, cited. Most often: the company sells a '
                                                    'competing retrieval API, or its product '
                                                    'demonstrably consumes no external information. '
                                                    "'No evidence of a search API' is NOT sufficient "
                                                    'and is listed under not_anti_signals.',
                                       'insufficient_evidence': 'Retrieval failed to establish what '
                                                                'the company does: the wrong entity, '
                                                                'almost no on-domain sources, or '
                                                                'failed requests. Reserve it for '
                                                                'genuine retrieval failure. If you can '
                                                                'describe the product from the '
                                                                'evidence, you can reach a verdict.'}},
    'recent_developments': [   {   'date': '2026-09-19',
                                   'event': 'Linkup Research released SPARSEUP, a 149M-parameter '
                                            'open-source sparse embedding model on ModernBERT, Apache '
                                            '2.0, published on Hugging Face. Blog post dated '
                                            '2026-09-17. Linkup reports 56.4 nDCG@10 on BEIR-13 and '
                                            'claims it is the strongest public vocabulary-based sparse '
                                            'encoder under 150M parameters (vendor claim).',
                                   'source': 'CTX-12, CTX-13',
                                   'sales_relevance': 'Useful credibility signal with technical '
                                                      'buyers: the team publishes retrieval research, '
                                                      'not only an API.'},
                               {   'date': '2026-09-09',
                                   'event': 'Launched Linkup Flash. Linkup reports under 200ms at the '
                                            'median (p50), measured client-side. Flash is not priced '
                                            'on the public pricing page.',
                                   'source': 'CTX-13',
                                   'sales_relevance': 'Relevant to prospects where per-query latency '
                                                      'sits in a user-facing loop, such as voice, chat '
                                                      'or in-session enrichment.'},
                               {   'date': '2026-03-03',
                                   'event': 'Announced $10M seed led by Gradient.',
                                   'source': 'CTX-04'},
                               {   'date': '2026-02-10',
                                   'event': 'Competitor Tavily agreed to be acquired by Nebius.',
                                   'source': 'CTX-10'}],
    'sources': [   {   'id': 'CTX-01',
                       'url': 'https://www.linkup.so/',
                       'type': 'vendor',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-02',
                       'url': 'https://docs.linkup.so/pages/documentation/get-started/introduction',
                       'type': 'vendor docs',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-03',
                       'url': 'https://docs.linkup.so/pages/documentation/endpoints/search/reference',
                       'type': 'vendor docs',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-04',
                       'url': 'https://www.linkup.so/blog/linkup-raises-10m-seed-to-build-web-search-for-ai',
                       'type': 'vendor',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-05',
                       'url': 'https://www.linkup.so/pricing',
                       'type': 'vendor',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-06',
                       'url': 'https://www.linkup.so/sales-agent-ai-sdr',
                       'type': 'vendor case study',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-07',
                       'url': 'https://www.linkup.so/case-studies',
                       'type': 'vendor',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-08',
                       'url': 'https://www.linkup.so/benchmarks',
                       'type': 'vendor, self-run',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-09',
                       'url': 'https://www.linkup.so/blog',
                       'type': 'vendor',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-10',
                       'url': 'https://nebius.com/newsroom/nebius-announces-agreement-to-acquire-tavily-to-add-agentic-search-to-its-ai-cloud-platform',
                       'type': 'third-party primary',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-11',
                       'url': 'https://www.bloomberg.com/news/articles/2026-02-10/nebius-agrees-to-buy-ai-agent-search-company-tavily-for-275-million',
                       'type': 'press, headline only, not read in full',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-12',
                       'url': 'https://www.marktechpost.com/2026/09/19/linkup-research-releases-sparseup/',
                       'type': 'press',
                       'accessed': '2026-09-21'},
                   {   'id': 'CTX-13',
                       'url': 'https://www.linkup.so/blog/introducing-sparseup-by-linkup',
                       'type': 'vendor',
                       'accessed': '2026-09-21'}],
    'verification': {   'verified_on': '2026-09-21',
                        'method': 'Independent adversarial re-check of every claim against its cited '
                                  'source.',
                        'corrections_applied': [   'SimpleQA 94% F1 belongs to the Fast tier, not '
                                                   'Flash',
                                                   'Artisan uses standard and deep search modes, not '
                                                   'standard alone',
                                                   'Flash latency restated as p50, self-measured '
                                                   'client-side',
                                                   'Search per-request pricing scoped to '
                                                   'Fast/Standard/Deep; Flash unpriced publicly',
                                                   'Homepage logos separated from published case '
                                                   'studies',
                                                   'IP whitelisting demoted to unconfirmed',
                                                   '1.2: ICP rewritten after four of five providers '
                                                   'applied a competitor test rather than a buyer test '
                                                   'to a GTM platform whose shape matches published '
                                                   'Linkup customers Artisan and Pennylane'],
                        'known_gaps': [   'No benchmark on the Linkup site carries a date.',
                                          'CTX-11 (Bloomberg) is paywalled; the $275M figure is '
                                          'attributed to Bloomberg, not to Nebius, who did not '
                                          'disclose it.']}}

# Deterministic serialisation. sort_keys makes the hash stable across Python versions.
CONTEXT_JSON = json.dumps(LINKUP_CONTEXT, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
CONTEXT_SHA256 = hashlib.sha256(CONTEXT_JSON.encode("utf-8")).hexdigest()


def context_provenance() -> dict:
    """Small manifest recorded on every run so saved runs stay comparable."""
    return {
        "context_version": CONTEXT_VERSION,
        "context_sha256": CONTEXT_SHA256,
        "context_built_at": LINKUP_CONTEXT["built_at"],
        "context_source_count": len(LINKUP_CONTEXT["sources"]),
    }
